### ISSUE TITLE
The bad results in the wave equation

### ISSUE THREAD

**Issue by yujingyan222** [ShotaDeguchi/PINN_TF2#3]
Dear @ShotaDeguchi ,
Thanks for the innovative contribution. I tried to run the wave equation 2D but I get bad results at t =5.0s. I don't modify the code. Could you please tell me why? Thanks a lot. 
![t=5](https://user-images.githubusercontent.com/107137942/172671879-85d1a45b-9829-4adc-a481-8b970774f215.png)

**Comment by ShotaDeguchi** [comment]
Thank you for reaching out. I got a similar result, however, I'm currently working on another project. I will fix and update once it's over.

**Comment by yujingyan222** [comment]
Thanks for your reply.

> Thank you for reaching out. I found a bug, and have been working. I will update once I'm done fixing it.

**Comment by ShotaDeguchi** [comment]
Fixed. It was due to bad boundary treatment. Please try again and see the result.

**Comment by yujingyan222** [comment]
> Fixed. It was due to bad boundary treatment. Please try again and see the result.

Dear @ShotaDeguchi ,
thanks a lot!
