### ISSUE TITLE
Saving weights and biases after training

### ISSUE THREAD

**Issue by Abhishekc95** [ShotaDeguchi/PINN_TF2#9]
Thank you for the PINN code TF2.0
I would like to know how to save weights and biases after training the PINN.
I see in the Class PINN of 03_wave file, you use the tf.keras.optimizer. In the train() method how do i get optimized weights and biases?

**Comment by ShotaDeguchi** [comment]
Thanks for your comment. 

The code you're referencing is a bit outdated. I recommend checking out a more recent version of the PINN implementation here: [DN_PINN](https://github.com/ShotaDeguchi/DN_PINN). This version includes a cleaner implementation and covers saving and loading models.

You could also reference TensorFlow’s [guide](https://www.tensorflow.org/tutorials/keras/save_and_load).

**Comment by Abhishekc95** [comment]
Just another request.
In the readme section, the link to english version downloads japanese version of paper. Can you please share english version pdf?

**Comment by ShotaDeguchi** [comment]
Unfortunately, is entirely written in Japanese, with only the abstract available in English. 

Apologies for the inconvenience.

**Comment by Abhishekc95** [comment]
Alright, thank you
